apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - migrate-job.yaml
  - ingestion-api.yaml
  - log-processor.yaml
  - query-api.yaml
  - dashboard.yaml
  - ingress.yaml
# secret.example.yaml is intentionally omitted. Create pulselog-secrets out of band.
